namespace VPRFORALL
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.statusStrip2 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.statusStrip1.SuspendLayout();
            this.statusStrip2.SuspendLayout();
            this.SuspendLayout();
            // 
            // statusStrip1
            // 
            this.statusStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel1});
            this.statusStrip1.Location = new System.Drawing.Point(0, 230);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(463, 25);
            this.statusStrip1.TabIndex = 0;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(151, 20);
            this.toolStripStatusLabel1.Text = "toolStripStatusLabel1";
            // 
            // textBox1
            // 
            this.textBox1.Enabled = false;
            this.textBox1.Location = new System.Drawing.Point(363, 46);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(63, 22);
            this.textBox1.TabIndex = 1;
            this.textBox1.Visible = false;
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(127, 86);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(230, 22);
            this.textBox2.TabIndex = 2;
            this.textBox2.Text = "Vendég Neve:";
            // 
            // textBox3
            // 
            this.textBox3.Location = new System.Drawing.Point(127, 126);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new System.Drawing.Size(230, 22);
            this.textBox3.TabIndex = 3;
            this.textBox3.Text = "Vendég Cég Neve:";
            // 
            // textBox4
            // 
            this.textBox4.Location = new System.Drawing.Point(127, 169);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new System.Drawing.Size(230, 22);
            this.textBox4.TabIndex = 4;
            this.textBox4.Text = "Ellenőrzés oka";
            // 
            // statusStrip2
            // 
            this.statusStrip2.Dock = System.Windows.Forms.DockStyle.Top;
            this.statusStrip2.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.statusStrip2.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel3});
            this.statusStrip2.Location = new System.Drawing.Point(0, 0);
            this.statusStrip2.Name = "statusStrip2";
            this.statusStrip2.Size = new System.Drawing.Size(463, 25);
            this.statusStrip2.TabIndex = 5;
            this.statusStrip2.Text = "statusStrip2";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(151, 20);
            this.toolStripStatusLabel3.Text = "toolStripStatusLabel3";
            // 
            // comboBox1
            // 
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "Abdel-Halim Zsolt EGE EgrP/W153",
            "Abonyi Oliver EGE EgrP/ENG3",
            "Acs Zoltan EGE EgrP/LOM",
            "Alfoeldi Csaba EGE EgrP/TEF11",
            "Almasi Zsofia EGE CP/PPP22-ER",
            "Amit Arpad EGE EgrP/W112",
            "Antal Balazs EGE EgrP/MOE11",
            "Antal Csaba EGE EgrP/LOM",
            "Antal Gabor EGE EgrP/TEF3",
            "Antal Laszlo EGE EgrP/TEF3",
            "Antal Zsolt EGE CP/PIR34-EE *",
            "Apostol Bence EGE CP/PQA1-Egr",
            "Apostol Bertalan EGE AS/QMP-Egr",
            "Asztalos Miklos EGE EgrP/W145",
            "Bacsur Jozsef EGE EgrP/W154",
            "Bahor Hunor EGE EgrP/W152",
            "Bajari Robert EGE EgrP/W155",
            "Bajzat Judit EGE AS/QMC2-Egr",
            "Bajzat Krisztian EGE EgrP/MFO3",
            "Bajzath Tibor EGE EgrP/TEF11",
            "Balazs Gabor EGE EgrP/ENG",
            "Balazs Gellert EGE EgrP/ENG1",
            "Balazs Jozsef EGE CP/PQA1-Egr",
            "Balazs Peter EGE CP/PPP22-ER *",
            "Balazs Viktor EGE EgrP/TEF3",
            "Balazs Zoltan EGE AS/QMC3-Egr",
            "Balog Tamas EGE AS/QMP-Egr",
            "Balogh Gabor EGE AS/QMC3-Egr *",
            "Balogh Gina EGE EgrP/LOM",
            "Balogh Imre Sandor EGE EgrP/TEF3",
            "Balogh Jozsef EGE EgrP/TEF3",
            "Balogne Juhasz Judit EGE EgrP/CTG3 *",
            "Ban Attila EGE EgrP/W126",
            "Banda Fanni EGE EgrP/MSE3",
            "Banka Andrea EGE EgrP/FIN1 *",
            "Bankane Szel Katalin Maria EGE EgrP/FIN1 *",
            "Banyai Janos EGE EgrP/W191",
            "Banyai Karoly Robert EGE CP/PQA-Egr",
            "Barati Valeria EGE EgrP/LOP8",
            "Barczi Balazs EGE EgrP/PJM *",
            "Bardos Fruzsina EGE EgrP/MOE11",
            "Barocsi Andras EGE EgrP/TEF3",
            "Barta Gabor EGE EgrP/W146",
            "Bartalus Barnabas EGE EgrP/TEF3",
            "Bartfai Peter EGE EgrP/W112",
            "Bartok Laszlo EGE EgrP/TEF12",
            "Basso Stefan EGE EgrP/PC *",
            "Bata Gabriella EGE EgrP/HRL3 *",
            "Bata Janos EGE EgrP/TEF3",
            "Batta Gabor EGE CP/PQA1-Egr",
            "Becsi Rozalia EGE EgrP/LOP1",
            "Becskei Miklos EGE EgrP/MFE3",
            "Bedak-Toth Zoltan EGE EgrP/MSE2 *",
            "Bekenyi Henrietta EGE EgrP/HRL3 *",
            "Benko Zoltan EGE EgrP/TEF3",
            "Benyus Rita EGE EgrP/LOI *",
            "Berecz Gabor EGE EgrP/MOE23",
            "Berecz Karoly EGE EgrP/PJM",
            "Bereczki Antal EGE AS/QMC1-Egr",
            "Beres Norbert EGE EgrP/W1711",
            "Besenyei Bence EGE EgrP/W153",
            "Bilak Tamas EGE EgrP/W146",
            "Bilban Nihan EGE EgrP/LOP7",
            "Biri Fruzsina EGE EgrP/MOE23",
            "Birinyi Istvan EGE EgrP/W154",
            "Biro Attila EGE EgrP/LOM",
            "Biro Zsolt EGE EgrP/MFE3",
            "Bodi Attila EGE EgrP/W1711",
            "Bodis Bela EGE EgrP/W145",
            "Bodnar Arnold EGE EgrP/W135",
            "Bodnar Zoltan Viktor EGE EgrP/PJM",
            "Bodo Nelli EGE EgrP/W1712",
            "Bodon Istvan EGE EgrP/W153",
            "Bogar Erika EGE AS/QMM1-Egr",
            "Boldizsar Ferenc EGE EgrP/LOP7",
            "Boldizsar Gabor EGE CP/PQA1-Egr *",
            "Boldizsar Sandor EGE EgrP/W154",
            "Bolyos Erik Laszlo EGE EgrP/TEF3",
            "Borbely Zsolt EGE EgrP/W126",
            "Bordacs Ferenc EGE EgrP/W152",
            "Borics Adam EGE EgrP/W1751",
            "Boros Csaba EGE EgrP/LOI",
            "Bota Andras EGE EgrP/LOI",
            "Bota Judit EGE EgrP/PJ-CFA *",
            "Bota Krisztian EGE EgrP/TEF12",
            "Bota Noemi EGE EgrP/LOM",
            "Bota Sandor Levente EGE EgrP/W135",
            "Botane Molnar Judit EGE EgrP/MOE12 *",
            "Bozsik Beata EGE EgrP/CTG3 *",
            "Bozsik Csaba EGE EgrP/TEF3",
            "Bozso Zoltan EGE CI/CWR4-HU *",
            "Bozsone Fehervari Anett EGE EgrP/LOP8",
            "Bukovinszky Tibor EGE AS/QMC3-Egr",
            "Bukta Attila EGE EgrP/LOP7",
            "Bukta Ferenc EGE EgrP/W1751",
            "Bukulyi Attila EGE EgrP/W191",
            "Burkus Nora EGE EgrP/HRL2 *",
            "Csacsko Richard EGE CP/PQA1-Egr",
            "Csaki Mihalyne EGE AS/QMM5-Egr",
            "Csaki Tamas EGE CI/CWR4-HU *",
            "Csanadi David EGE AS/QMP-Egr",
            "Csati Peter EGE EgrP/MOE11",
            "Csato Emilia Ibolya EGE EgrP/CTG2 *",
            "Csato Sandor EGE AS/QMP-Egr",
            "Csato Tamas EGE EgrP/LOM",
            "Cseh Daniel EGE EgrP/W165",
            "Cseh Laszlo EGE EgrP/W155",
            "Csehok Laszlo EGE EgrP/W1751",
            "Csenkei Soma EGE CP/PPP22-ER",
            "Cseresznye Balazs EGE EgrP/W1711",
            "Csige Marton EGE EgrP/MOE11",
            "Csivincsik Balint EGE EgrP/W155",
            "Csoke Martin EGE EgrP/W146",
            "Csombo Gyoergy EGE EgrP/LOM",
            "Csonka David EGE CP/PQA-Egr *",
            "Csorba Laszlo EGE EgrP/TEF11",
            "Csufor Gabor EGE EgrP/W1712",
            "Csulak Erno EGE EgrP/LOM",
            "Czako Balazs EGE EgrP/LOP7",
            "Czibere Sandor EGE EgrP/TEF12",
            "Cziberene Bota Szilvia EGE EgrP/LOP8",
            "Cziner Gyoergy EGE EgrP/TEF12",
            "Dancso Csaba EGE AS/QMP-Egr",
            "Dániel Csuhaj EGE",
            "Dargai Akos EGE EgrP/MOE12 *",
            "Dargai Oliver EGE EgrP/MSE1 *",
            "Darnai Tibor EGE EgrP/TEF3 *",
            "Daruka Judit EGE EgrP/LOP8",
            "David Arpad EGE CI/CWR4-HU *",
            "Demeter Zoltan EGE EgrP/PJ-CFA *",
            "Der Adam EGE EgrP/LOM",
            "Der Zsolt EGE EgrP/TEF3",
            "Divinyi Laszlo Pal EGE EgrP/MOE11",
            "Dobi Jozsef EGE EgrP/TEF3",
            "Dobo Istvan EGE EgrP/W1712",
            "Dobos Ferenc EGE EgrP/CTG1",
            "Dobos Gabor EGE EgrP/W152",
            "Dolonai Lidia EGE EgrP/PT",
            "Doman Gabor EGE EgrP/TEF3 *",
            "Domanne Molnar Eva EGE EgrP/W1751",
            "Dombi Gabor EGE EgrP/TEF3 *",
            "Dongo Peter EGE EgrP/MOE3",
            "Dorko Gabor EGE EgrP/MOE23",
            "Dorkone Kali Eszter EGE EgrP/LOM",
            "Egedne Szecsi Beatrix EGE EgrP/W1751",
            "Erdei Lajos EGE EgrP/W145",
            "Erdelyi Pal EGE EgrP/LOP7",
            "Eros Peter Istvan EGE EgrP/TEF3",
            "Eros Peter Istvanne EGE AS/QMM1-Egr",
            "Ersek Adam EGE EgrP/LOM",
            "Farago Csaba EGE EgrP/FIN1",
            "Farkas Emese EGE EgrP/HRL3 *",
            "Farkas Istvan EGE CP/PMQ6-AS *",
            "Farkas Kristof Jeno EGE EgrP/ENG",
            "Farkas Robert Krisztian EGE EgrP/LOP7",
            "Farkas Zoltan EGE EgrP/W146",
            "Fazekas Tamas EGE EgrP/W1751",
            "Feher Robert EGE EgrP/W1751",
            "Fekete Gabor EGE EgrP/PJ-AM",
            "Fekete Lajos EGE EgrP/TEF3",
            "Felegyhazi Imre EGE EgrP/TEF11",
            "Ferencz Istvan EGE AS/QMP-Egr *",
            "Ferencz Peter EGE AS/QMP-Egr",
            "Fodor Istvan EGE EgrP/LOP1",
            "Foeldhazi Akos EGE EgrP/BPS",
            "Fonagy Adam Vilmos EGE EgrP/W165",
            "Fonagy Mark EGE EgrP/W1751",
            "Fonyad Tibor EGE EgrP/TEF11 *",
            "Frecsko Erika EGE EgrP/HRL3 *",
            "Fridel-Kovacs Katalin Maria EGE EgrP/CTG3 *",
            "Frona Laszlo EGE AS/QMM5-Egr",
            "Fuchs Gabor Andor EGE EgrP/ENG2",
            "Fuegedi Bence EGE EgrP/W1711",
            "Fueko Gabor EGE EgrP/LOM",
            "Fueloep Erika EGE EgrP/W153",
            "Fueloep Peter EGE EgrP/W151",
            "Gacs Martin EGE EgrP/W165",
            "Gacsal Denes EGE EgrP/ENG2 *",
            "Gal David EGE EgrP/TEF3",
            "Gal Priscilla EGE EgrP/FIN3 *",
            "Gal Tamas EGE EgrP/MOE11",
            "Galea Janos EGE EgrP/ENG1",
            "Gallasy Tamas EGE EgrP/W152",
            "Gallik Csilla Maria EGE EgrP/PJM *",
            "Galne Antal Eva EGE EgrP/HRL2 *",
            "Gaspar Istvan EGE EgrP/W145",
            "Gaspar Robert EGE EgrP/W1711",
            "Gavaller Jozsef EGE AS/QMM-Egr *",
            "Gazso Krisztian EGE EgrP/W153",
            "Geczy Janos EGE EgrP/W155",
            "Goemoeri Laszlo EGE EgrP/W155",
            "Golyane Jaszfalusi Andrea EGE EgrP/LOP8",
            "Golyha Gabriella EGE EgrP/W1751",
            "Gor Mate EGE EgrP/MOE22",
            "Goz Istvan EGE EgrP/W152",
            "Greczi Tekla EGE AS/QMC3-Egr",
            "Grosz Tibor EGE EgrP/W1751",
            "Gulyas Eva EGE EgrP/CTG1",
            "Gulyas Levente EGE EgrP/LOM",
            "Guzsvany Zsolt EGE AS/QMC1-Egr",
            "Gyarfas Marcell EGE EgrP/W1711",
            "Gyarmati Jozsef EGE EgrP/LOM",
            "Gyujtone Jonas Maria EGE CP/PQA1-Egr",
            "Gyulai Gabor EGE EgrP/TEF3",
            "Gyurko-Kiss Timea EGE EgrP/LOP8",
            "Hagen Istvan Zsolt EGE EgrP/LOM",
            "Hager Istvan EGE EgrP/MOE11",
            "Hajdu Krisztian EGE EgrP/W155",
            "Hajdu Lilla EGE CP/PQA1-Egr",
            "Halasz Andras EGE EgrP/W154",
            "Halko Gergo EGE EgrP/W1712",
            "Hamrik Ferenc EGE EgrP/W1712",
            "Hanzo Tamas EGE EgrP/W152",
            "Havasi Mate EGE EgrP/PC *",
            "Hegyi Peter EGE EgrP/LOM",
            "Helgert Akos EGE EgrP/MOE11 *",
            "Helli Zoltan EGE EgrP/W155",
            "Herczeg Viktor EGE EgrP/CTG2 *",
            "Hermann Zsolt EGE EgrP/ENG4",
            "Hettinger Márk EGE",
            "Hevesi Zsolt EGE EgrP/LOM",
            "Hodosi Peter EGE AS/QMC2-Egr",
            "Hoeflinger Ferenc Istvan EGE EgrP/W152",
            "Hollo Tibor EGE EgrP/W155",
            "Horneczki Gabor EGE EgrP/HSE",
            "Hornok Daniel EGE EgrP/CTG2",
            "Hornyak Anett EGE EgrP/HSE",
            "Horvath Gabor EGE EgrP/MOE12",
            "Horvath Gabor EGE EgrP/W135",
            "Horvath Roland EGE EgrP/W1712",
            "Horvath Viktor EGE EgrP/MOE3",
            "Hosso David EGE EgrP/W132",
            "Hugyina Laszlo EGE EgrP/W152",
            "Husonyica Zsolt EGE AS/QMM5-Egr *",
            "Huszar Gyoergy EGE EgrP/W1751",
            "Imre Krisztian Laszlo EGE EgrP/W144",
            "Ipacs Martin EGE EgrP/W146",
            "Jacso Szabina EGE EgrP/FIN2 *",
            "Jancso Zoltan EGE EgrP/LOM",
            "Jen Peter Robert EGE EgrP/ENG2",
            "Judak Imre EGE EgrP/PJM",
            "Juhasz Attila Gyoergy EGE CI/CWR4-HU *",
            "Juhasz Judit EGE EgrP/TEF",
            "Juhasz Laszlo EGE CP/PMQ6-AS",
            "Juhasz Laszlo EGE EgrP/TEF3",
            "Juhasz Laszlo EGE EgrP/W191",
            "Juhasz Tamas EGE AS/QMC2-Egr",
            "Kaczur Attila EGE EgrP/FIN",
            "Kakuk Adrienn EGE EgrP/FIN1 *",
            "Kakuk Robert EGE EgrP/W1712",
            "Kakuk Roland EGE AS/QMC1-Egr",
            "Kakuk Tibor EGE EgrP/MOE22",
            "Kakuk Zoltan EGE EgrP/LOM",
            "Kalotai Tamas EGE EgrP/TEF3",
            "Kantor Gergo EGE EgrP/LOM",
            "Kanyo Petra EGE EgrP/W145",
            "Kapitany Akos EGE EgrP/TEF3",
            "Karanyicz Erik EGE EgrP/W1712",
            "Karanyicz Peter EGE EgrP/W126",
            "Karcsai Attila EGE EgrP/CTG2 *",
            "Kardos Gabor EGE EgrP/TEF3",
            "Karnizs Gabor EGE EgrP/W155",
            "Kasa Erika EGE EgrP/BPS",
            "Kasa Laszlo EGE AS/QMP-Egr *",
            "Kasa-Gyimesi Orsolya EGE EgrP/LOP8",
            "Katona Janos EGE EgrP/TEF3",
            "Katona Rahel Csenge EGE EgrP/LOG *",
            "Katona Roland EGE EgrP/W135",
            "Katona Tibor EGE EgrP/W1712",
            "Kecsmar Zoltan EGE EgrP/W126",
            "Kelemen Csaba EGE AS/QMM5-Egr",
            "Kelemen Gergo EGE EgrP/W152",
            "Kerekes Ferenc EGE EgrP/W1711",
            "Kerekgyarto David EGE EgrP/W193",
            "Kernacs Laszlo EGE EgrP/TEF3",
            "Kiraly Nikolett EGE EgrP/MOE11",
            "Kirzsa Peter EGE EgrP/W152",
            "Kis Balint EGE EgrP/W145",
            "Kis Zoltan EGE CI/CWR4-HU *",
            "Kis Zoltan EGE EgrP/W193",
            "Kisne Eros Eszter EGE EgrP/LOP7",
            "Kiss Bence EGE EgrP/MOE12",
            "Kiss David Ferdinand EGE EgrP/CTG2 *",
            "Kiss Istvan EGE EgrP/MOE11",
            "Kiss Janos EGE AS/QMP-Egr",
            "Kiss Krisztian EGE EgrP/W193",
            "Kiss Laszlo EGE EgrP/W135",
            "Kiss Richard EGE EgrP/W191",
            "Kiss Sandor EGE EgrP/W117",
            "Kiss Szabolcs EGE EgrP/W117",
            "Kiss Tibor EGE EgrP/MSE1 *",
            "Kiss Zsolt EGE AS/QMM1-Egr *",
            "Kiss-Orosz Peter EGE EgrP/LOP8",
            "Kisvarga Jozsef EGE EgrP/W1712",
            "Klinzing Paul EGE EgrP/PT *",
            "Klubuk Imre EGE AS/QMP-Egr",
            "Kocsa Istvanne EGE EgrP/HRL2 *",
            "Kocsa Richard EGE EgrP/W152",
            "Kocsis Balazs EGE AS/QMC1-Egr",
            "Kocsis Jozsef EGE EgrP/W152",
            "Koedmoen Jozsef EGE EgrP/W1712",
            "Koedmoen Tamas EGE EgrP/W1712",
            "Koevesdy Lorant EGE EgrP/MOE11",
            "Kohari Edit EGE EgrP/LOP7",
            "Kolevszki Daniel EGE EgrP/W1751",
            "Komjathy Balazs EGE AS/QMC3-Egr",
            "Koncz Zoltan EGE CP/PQA1-Egr",
            "Koncz Zoltan Rafael EGE EgrP/LOP7",
            "Koos Istvan EGE EgrP/TEF3",
            "Koos Peter Laszlo EGE EgrP/LOM",
            "Korcsog Zoltan EGE EgrP/W132",
            "Kormos Gergely EGE CP/PPP22.1-ER",
            "Kormos Laszlo EGE CP/PIR34-EE",
            "Kormos Tamas EGE EgrP/W135",
            "Kormos Tibor EGE EgrP/W146",
            "Korodi Tamas EGE EgrP/MOE23 *",
            "Korponyi Kristof EGE EgrP/TEF3",
            "Korsos Henrietta EGE EgrP/FIN3 *",
            "Kosa Istvan EGE AS/QMC2-Egr",
            "Kosa Robert EGE AS/QMP-Egr",
            "Kosztelnik Arpad EGE AS/QMP-Egr *",
            "Kovacs Agnes EGE EgrP/W154",
            "Kovacs Andras Marcell EGE EgrP/CTG2 *",
            "Kovacs Balazs EGE EgrP/W151",
            "Kovacs Bela EGE EgrP/TEF3",
            "Kovacs Csaba EGE AS/QMC3-Egr",
            "Kovacs Csaba Renato EGE EgrP/W155",
            "Kovacs Jozsef EGE EgrP/MOE3",
            "Kovacs Jozsef EGE EgrP/W153",
            "Kovacs Krisztian EGE",
            "Kovacs Krisztian EGE EgrP/W1751",
            "Kovacs Krisztina EGE EgrP/MOE11 *",
            "Kovacs Lorant EGE EgrP/W1711",
            "Kovacs Loretta EGE EgrP/PT",
            "Kovacs Rita EGE EgrP/HRL3 *",
            "Kovacs Tamas EGE CI/CWR4-HU *",
            "Kovacs Tibor EGE EgrP/TEF3",
            "Kovacs Timea EGE EgrP/PC *",
            "Kovács Zoltán EGE",
            "Kovacs Zoltan EGE EgrP/MFE3",
            "Kovacs Zoltan EGE EgrP/W1711",
            "Kovacs-Csuvarszki Rita EGE EgrP/MOE22 *",
            "Kovacs-Majoros Katalin EGE EgrP/PT",
            "Kozma Jozsef EGE EgrP/TEF3",
            "Kreidl Frigyes EGE EgrP/W146",
            "Kriston Norbert Ferenc EGE EgrP/W153",
            "Kriston Zsolt EGE EgrP/W153",
            "Kroll Marianne EGE EgrP/LOP8",
            "Krutilla Robert EGE AS/QMC2-Egr",
            "Kuborczik Attila EGE EgrP/W145",
            "Kuerti Patrik EGE EgrP/W135",
            "Kugyela Peter Attila EGE EgrP/TEF3 *",
            "Kuli Peter EGE EgrP/W132",
            "Kun Zoltan EGE CP/PQA1-Egr",
            "Kurilla Robert EGE EgrP/ENG4",
            "Kurucz Erika EGE EgrP/MSE3 *",
            "Laczko Adam EGE AS/QMC3-Egr",
            "Laczko Gyoergy EGE EgrP/MOE12",
            "Lakatos Adam Tibor EGE CP/PPP22.1-ER",
            "Laszlo Alexandra EGE EgrP/LOI",
            "Lates Matyas Szilveszter EGE EgrP/LOM",
            "Lenart Pal Jozsef EGE EgrP/LOP7",
            "Lenart Peter EGE AS/QMC2-Egr *",
            "Lengyel Norbert EGE AS/QMP-Egr",
            "Lengyel Zsofia EGE CP/PQA1-Egr",
            "Levai Adam EGE EgrP/ENG3",
            "Levay Melinda EGE AS/QMM1-Egr *",
            "Linkecs Adam EGE EgrP/LOM",
            "Linkecs-Sveda Edina EGE EgrP/LOM",
            "Lipcsei Gergely EGE EgrP/W1712",
            "Liptai Tibor EGE AS/QMC1-Egr",
            "Locsei Tamas EGE EgrP/TEF12",
            "Loj Lajos EGE EgrP/W117",
            "Lorincz Daniel EGE EgrP/W146",
            "Ludanyi Gergo Gyula EGE EgrP/W1711",
            "Ludanyi Katalin EGE EgrP/PC *",
            "Ludvig Adam EGE EgrP/LOP2",
            "Luhaly Attila EGE EgrP/PJM",
            "Lukacs Attila EGE AS/QMM5-Egr",
            "Lukacs Laszlo EGE EgrP/W154",
            "Lukacs Mate EGE EgrP/PT",
            "Lukacsi Istvan EGE EgrP/TEF3",
            "Magyar Balazs EGE EgrP/W193",
            "Magyar Gabor EGE EgrP/W135",
            "Magyari Robert EGE CP/PPP22-ER",
            "Major Kitti EGE EgrP/CTG2 *",
            "Malicsek Zoltan EGE EgrP/W191",
            "Marczis Csaba EGE EgrP/W146",
            "Marczisne Aszodi Anita EGE EgrP/MOE22",
            "Marmoly Gyoergy EGE EgrP/TEF3",
            "Marquardt Tamas EGE AS/QMC3-Egr",
            "Marton Zsolt EGE AS/QMC1-Egr",
            "Martonne  Ocsai Katalin EGE EgrP/MOE23",
            "Mata Erzsebet EGE EgrP/LOM",
            "Mata Robert EGE EgrP/TEF3",
            "Matane Toth Ildiko EGE EgrP/LOM",
            "Mate Otto EGE EgrP/LOP7",
            "Matejka Istvan Gabor EGE EgrP/MOE12",
            "Mattyasovszky Katalin EGE EgrP/CTG1",
            "Matusz Peter EGE EgrP/ENG4",
            "Matyko Bianka Melinda EGE EgrP/FIN2 *",
            "Medve Gyula EGE EgrP/W153",
            "Melichar David EGE EgrP/TEF3",
            "Mentusz Adam EGE EgrP/MOE12",
            "Meszaros Adrienn Beatrix EGE EgrP/HRL2 *",
            "Meszaros Szabolcs Gabor EGE AS/QMC3-Egr",
            "Mezei Peter EGE EgrP/MOE11",
            "Mezes Andras EGE EgrP/W1751",
            "Mezo Peter EGE AS/QMC1-Egr",
            "Miko Andrea EGE EgrP/LOM",
            "Miltenyi Mate EGE EgrP/PT",
            "Minarovits Pal EGE EgrP/TEF3",
            "Minarovits Szilard EGE EgrP/MOE11",
            "Mirkoczky Laszlo EGE EgrP/W112",
            "Molnar Adam EGE EgrP/ENG4",
            "Molnar Adam EGE EgrP/MOE12",
            "Molnar Andras EGE CP/PMQ6-AS",
            "Molnar Eva EGE EgrP/LOP8",
            "Molnar Gabor EGE EgrP/MOE12",
            "Molnar Gyozo EGE CP/PQA1-Egr",
            "Molnar Krisztian Balazs EGE EgrP/W1712",
            "Molnar Krisztian EGE EgrP/TEF3 *",
            "Molnar Laszlo EGE EgrP/LOP *",
            "Molnar Mihaly EGE AS/QMC1-Egr *",
            "Molnar Peter EGE EgrP/W152",
            "Molnar Tamas EGE EgrP/W155",
            "Molnar-Toth Peter EGE AS/QMM5-Egr",
            "Montvai Erika EGE AS/QMM1-Egr",
            "Mora Jozsef EGE EgrP/W144",
            "Morvai Viktoria Adrienn EGE EgrP/TEF12",
            "Munkacsi Erika EGE EgrP/FIN2 *",
            "Muranyi Jozsef EGE EgrP/BPS *",
            "Muranyi Jr Jozsef EGE EgrP/PJM *",
            "Muranyi Roland EGE EgrP/TEF3",
            "Muranyi Zoltan EGE EgrP/ENG4",
            "Nadra Gyula Sandor EGE EgrP/MOE11",
            "Nagy Andras EGE EgrP/ENG3",
            "Nagy Anita EGE EgrP/HRL3 *",
            "Nagy Arpad Laszlo EGE EgrP/ENG3",
            "Nagy Attila EGE EgrP/W1712",
            "Nagy Bela EGE EgrP/LOP7",
            "Nagy Endre EGE EgrP/LOP7",
            "Nagy Gergo EGE EgrP/TEF12",
            "Nagy Jozsef EGE EgrP/W132",
            "Nagy Krisztian EGE EgrP/W1711",
            "Nagy Laszlo EGE AS/QMC3-Egr",
            "Nagy Laszlo EGE EgrP/MOE12",
            "Nagy Laszlo Ferenc EGE EgrP/TEF3",
            "Nagy Norbert EGE EgrP/ENG1",
            "Nagy Orsolya EGE EgrP/CTG3 *",
            "Nagy Peter EGE CI/CWR4-HU *",
            "Nagy Peter EGE EgrP/TEF3",
            "Nagy Peter EGE EgrP/W1712",
            "Nagy Rafael EGE EgrP/MFE3",
            "Nagy Robert EGE EgrP/W112",
            "Nagy Sandor Csaba EGE EgrP/MOE12 *",
            "Nagy Sandor EGE CP/PQA1-Egr",
            "Nagy Sandor EGE EgrP/W154",
            "Nagy Szabolcs EGE EgrP/W151",
            "Nagy Viktoria EGE EgrP/FIN1 *",
            "Nagy Zoltan Mihaly EGE EgrP/TEF3",
            "Nagy Zoltan Sandor EGE EgrP/ENG3",
            "Nagy Zsolt EGE EgrP/TEF3",
            "Nagy Zsuzsanna EGE EgrP/HRL *",
            "Nagyne Cseszneg Anita EGE EgrP/LOM",
            "Nagyne Reti Eva EGE AS/QMC3-Egr",
            "Nagyne Schmutzer Anita EGE EgrP/LOM",
            "Nagyne Szekely Andrea EGE EgrP/W1712",
            "Nelson Richard Pierre EGE EgrP/PJM",
            "Nemcsik Zsofia EGE EgrP/CFA",
            "Nemes Zsolt EGE EgrP/W117",
            "Nemeth Gabor EGE EgrP/MOE12 *",
            "Nemeth Gergely EGE EgrP/W151",
            "Nemeth Zsolt EGE EgrP/TEF *",
            "Nyari Rita EGE EgrP/LOP8",
            "OErdoeg Tamas EGE EgrP/W144",
            "Olah Krisztian Gyoergy EGE EgrP/TEF3",
            "Olah Viktor EGE CP/PQA1-Egr",
            "Olajos Istvan EGE EgrP/MOE22",
            "Omelka Balazs EGE AS/QMC3-Egr",
            "Oravecz Tamas EGE AS/QMP-Egr",
            "Orosz Csaba EGE EgrP/W135",
            "Orosz Istvan EGE EgrP/LOM",
            "Orosz Tamas Istvan EGE EgrP/MOE11",
            "Orosz Viktor EGE CP/PMQ6-AS",
            "Oszlanczi Gergo EGE AS/QMC1-Egr",
            "Osztroczki Zoltan EGE EgrP/W151",
            "Otterbach Wolfgang Dr. EGE EgrP/ENG *",
            "Ozse Gabor EGE EgrP/W135",
            "Padar Gergo EGE EgrP/W117",
            "Palfy Andras Miklos EGE EgrP/LOI",
            "Pálinkás András",
            "Palotai Tuende EGE EgrP/W132",
            "Pap Attila EGE EgrP/TEF3",
            "Pap Gabor EGE EgrP/ENG4",
            "Papp Bela EGE AS/QMC1-Egr",
            "Papp Benjamin EGE EgrP/MOE23",
            "Papp Dorisz EGE EgrP/TEF3 *",
            "Papp Gabor Gyoergy EGE CP/PPP22-ER *",
            "Papp Gergely EGE AS/QMC3-Egr",
            "Papp Marianna EGE EgrP/BPS",
            "Parizsa Balazs EGE EgrP/W1712",
            "Paszthy Edina EGE EgrP/CTG2 *",
            "Pasztor Istvan EGE EgrP/W1712",
            "Pasztor Nikolett EGE EgrP/CTG2 *",
            "Pasztor-Orosz Andrea EGE EgrP/CFA *",
            "Pataki Ferenc Gabor EGE CP/PQA1-Egr",
            "Patvaros Zoltan EGE AS/QMM5-Egr",
            "Pelle Tamas EGE EgrP/W146",
            "Perger Gabriella EGE EgrP/FIN1",
            "Pinter Laszlo EGE EgrP/TEF3",
            "Pinter Tamas EGE EgrP/TEF3",
            "Polonkai Zoltan EGE EgrP/W132",
            "Poschner Peter EGE AS/QMP-Egr",
            "Pota Zoltan EGE EgrP/LOM",
            "Prokaj Janosne EGE EgrP/CTG1 *",
            "Prokaj Krisztian EGE EgrP/LOM *",
            "Prokaj-Kovács Zsófia",
            "Pusztai Peter EGE EgrP/W151",
            "Puzsik Krisztian EGE EgrP/W151",
            "Racz Tamas EGE AS/QMM5-Egr",
            "Racz Tamas EGE EgrP/TEF3",
            "Rauscher Andrea EGE EgrP/LOP1",
            "Renn Dora EGE CP/PPP22-ER",
            "Repasi Istvan EGE CP/PMQ6-AS",
            "Restas Noemi EGE EgrP/LOP8",
            "Reti-Nagy Tamas EGE EgrP/MOE23",
            "Rigelne Zay Zita EGE AS/QMM5-Egr",
            "Riman Andras EGE EgrP/TEF11",
            "Rozsa Kornel EGE AS/QMP-Egr",
            "Rozsnaki Gabor EGE EgrP/W1712",
            "Rudnak Gyoergy EGE EgrP/W153",
            "Rugo Ferenc EGE EgrP/W1712",
            "Runge Thorsten EGE EgrP/CTG1 *",
            "Ruszkai Andrea EGE EgrP/TEF3 *",
            "Ruzsinszki Adam Jozsef EGE EgrP/W146",
            "Sagi Erika EGE EgrP/LOP1 *",
            "Sajgone Horvath Eszter EGE EgrP/MOE3",
            "Saly Attila EGE EgrP/W1712",
            "Sandor Adam EGE EgrP/MOE23",
            "Sandor Krisztian EGE EgrP/MOE12",
            "Sapi Gitta EGE EgrP/PJ-CFA *",
            "Sari Attila EGE EgrP/W112",
            "Sari Laszlo EGE EgrP/W154",
            "Sarkoezi Barbara EGE EgrP/FIN3 *",
            "Schindler Tibor EGE EgrP/W151",
            "Sebok Tamas EGE EgrP/MOE12",
            "Seiber Dora EGE EgrP/FIN3 *",
            "Sepsi Andrea EGE EgrP/LOP2",
            "Serfozo Marton EGE CI/CWR4-HU *",
            "Sike Attila EGE EgrP/W193",
            "Sike Viktor EGE EgrP/ENG4",
            "Sima Fanni EGE EgrP/MOE11",
            "Simon Adrian EGE CI/CWR4-HU",
            "Simon Ferenc EGE CP/PQA1-Egr",
            "Simon Jozsef EGE EgrP/W191",
            "Sinkovics Ferenc EGE EgrP/MOE11",
            "Somodi Judit EGE EgrP/FIN3 *",
            "Somogyi Laszlo EGE CP/PQA1-Egr",
            "Somogyvari Zoltan EGE EgrP/W117",
            "Sos-Fueloep Emese EGE EgrP/LOM",
            "Strigel Jozsef EGE EgrP/TEF12 *",
            "Suemegi Bence Andor EGE EgrP/W165",
            "Sueto David EGE EgrP/TEF3",
            "Sueveg Mihaly EGE EgrP/W155",
            "Surak Stefan EGE EgrP/ENG3 *",
            "Suszter Gyoergy Robert EGE AS/QMP-Egr",
            "Szabados Gabor Richard EGE EgrP/TEF3",
            "Szabo Aniko EGE EgrP/LOP2",
            "Szabo Denes EGE EgrP/MOE22",
            "Szabo Gabor EGE EgrP/TEF3",
            "Szabo Gabor EGE EgrP/W151",
            "Szabo Gergely EGE EgrP/TEF11",
            "Szabo Katalin EGE AS/QMM5-Egr *",
            "Szabo Kornel Sandor EGE EgrP/TEF11",
            "Szabo Laszlo EGE AS/QMC1-Egr",
            "Szabo Laszlo EGE EgrP/TEF3",
            "Szabo Marton EGE EgrP/MOE3",
            "Szabo Miklos EGE EgrP/ENG2",
            "Szabo Peter EGE EgrP/TEF12",
            "Szabo Robert EGE EgrP/LOM",
            "Szabo Roland Istvan EGE EgrP/TEF3",
            "Szabo Viktor EGE AS/QMP-Egr",
            "Szabo Zoltan EGE EgrP/TEF3",
            "Szabo Zoltan EGE EgrP/W135",
            "Szalai Szabolcs EGE EgrP/W145",
            "Szalkai Balazs EGE EgrP/W1751",
            "Szalmasne Devecseri Maria EGE CP/PMQ6-AS *",
            "Szaniszlo Zsolt EGE EgrP/TEF3",
            "Szanto Peter EGE EgrP/MOE12",
            "Szarka Barbara EGE EgrP/PT *",
            "Szarvas Kornel EGE EgrP/W126",
            "Szatmari Szabolcs EGE EgrP/W193",
            "Szecsi Petronella EGE EgrP/LOP2",
            "Szecsi Tibor Laszlo EGE EgrP/TEF3",
            "Szecsko Robert EGE EgrP/MOE3",
            "Szecsodi Istvan EGE EgrP/W126",
            "Szegedi Daniel EGE AS/QMP-Egr",
            "Szegho Zsolt EGE AS/QMC3-Egr",
            "Szekely Gabriella EGE EgrP/ENG2",
            "Szekeres Laszlo EGE AS/QMC2-Egr",
            "Szekrenyes Csaba Krisztian EGE EgrP/TEF3 *",
            "Szel Jozsef EGE CI/CWR4-HU *",
            "Szeles Gabor EGE EgrP/W155",
            "Szeles Tamas EGE EgrP/LOM",
            "Szentmiklossy Erika Theodora EGE AS/QMM5-Egr",
            "Szerencsi Gabor EGE EgrP/MFO3 *",
            "Szilagyi Norbert EGE EgrP/ENG2",
            "Szilagyi Richard EGE CI/CWR4-HU *",
            "Szilagyi Sandor EGE AS/QMC3-Egr",
            "Szilagyine Toth Agnes Maria EGE EgrP/LOP7",
            "Szilvasi Daniel EGE EgrP/W155",
            "Szilvasi Renato EGE EgrP/W144",
            "Szirze Tamas EGE EgrP/ENG3",
            "Szita Melinda EGE EgrP/PJ-AM",
            "Szlahorekne Helli Monika EGE EgrP/FIN3 *",
            "Szocs Eniko EGE AS/QMM1-Egr",
            "Szocs Laszlo EGE EgrP/W126",
            "Szoegedi Gabor Sandor EGE EgrP/TEF3",
            "Szojka Gabor EGE EgrP/W191",
            "Szollath Peter EGE EgrP/TEF3",
            "Szontagh Laszlo EGE EgrP/FIN *",
            "Szopko Attila EGE EgrP/W1712",
            "Sztaho Csaba EGE EgrP/W153",
            "Szunyi Attila EGE EgrP/W155",
            "Szunyi Attila EGE EgrP/W165",
            "Szuromi Szabolcs EGE CP/PPP22-ER",
            "Tagai Krisztian EGE EgrP/LOG *",
            "Takacs-Szepesi Ivett EGE EgrP/LOP2",
            "Tari Akos EGE CP/PIR34-EE",
            "Tarjanyi Laszlo EGE EgrP/W117",
            "Tarnoczi Tamas EGE EgrP/MOE11",
            "Telek Marta EGE EgrP/FIN2 *",
            "Tengely Zsolt EGE CP/PMQ6-AS",
            "Tilaji Zsolt EGE AS/QMM5-Egr",
            "Tisza Tibor EGE EgrP/W165",
            "Tobias Aliz EGE EgrP/LOP2",
            "Tobis Istvan EGE EgrP/W146",
            "Toerocsik Tibor EGE EgrP/W1751",
            "Toerocsikne Vass Ivett EGE EgrP/W1751",
            "Toeroek Attila EGE EgrP/W1712",
            "Toeroek Karoly EGE EgrP/W151",
            "Toeroek Tibor EGE EgrP/W153",
            "Toeroek Zsolt EGE EgrP/TEF3",
            "Torma Gabriella EGE AS/QMM1-Egr *",
            "Toth Attila EGE EgrP/W135",
            "Toth Balazs EGE EgrP/W152",
            "Toth Gabor Daniel EGE EgrP/MOE11",
            "Toth Gabor EGE EgrP/ENG4",
            "Toth Gyula EGE EgrP/W146",
            "Toth Laszlo EGE EgrP/ENG4",
            "Toth Mate EGE EgrP/BPS",
            "Toth Melinda EGE EgrP/LOP1",
            "Toth Robert EGE EgrP/W132",
            "Toth Sandor EGE EgrP/TEF11 *",
            "Toth Szabolcs EGE EgrP/MOE12",
            "Toth Tamas EGE AS/QMP-Egr",
            "Toth Tamas EGE EgrP/LOP2",
            "Toth Tibor EGE EgrP/LOP7",
            "Toth Zsuzsanna EGE EgrP/W1751",
            "Tothne Molnar Csilla EGE AS/QMC2-Egr",
            "Trenka Gergely Jozsef EGE EgrP/W144",
            "Tuerk Andras EGE EgrP/TEF3",
            "Turai Csaba EGE AS/QMC1-Egr",
            "UEveges Krisztian EGE CP/PMQ6-AS",
            "Ujj Lilla EGE AS/QMM-Egr",
            "Ujlaki Richard EGE EgrP/LOP7",
            "Usak Szilard EGE EgrP/MOE11",
            "Utassyne Hamar Maria EGE EgrP/W1712",
            "Uzelman Adam EGE EgrP/LOP7",
            "Vaczi Istvan EGE EgrP/LOM",
            "Vadaszi Gabor EGE EgrP/LOP1",
            "Vadaszi Gyula EGE EgrP/TEF3",
            "Vamos Istvan EGE EgrP/BPS",
            "Vamos Monika EGE EgrP/HRL3 *",
            "Vanczer Dora EGE CP/PQA1-Egr",
            "Vanko Zsolt EGE EgrP/CTG2 *",
            "Vankone Sallai Erzsebet EGE CP/PPP22-ER *",
            "Varga Akos EGE EgrP/MFE3",
            "Varga Attila EGE AS/QMM1-Egr",
            "Varga Attila EGE EgrP/MOE3",
            "Varga Balazs EGE EgrP/W1751",
            "Varga Balázsne EGE",
            "Varga Erika EGE EgrP/MOE3",
            "Varga Laszlo EGE EgrP/LOP7",
            "Varga Peter Balazs EGE EgrP/LOM",
            "Varga Tamas EGE EgrP/TEF3",
            "Varga Zsuzsa EGE CP/PMQ6-AS",
            "Vargyune Varga Orsolya EGE CP/PQA1-Egr",
            "Vari Mihaly Zsolt EGE EgrP/W1712",
            "Vas Peter Ferenc EGE EgrP/LOM",
            "Vas Robert EGE EgrP/MOE11 *",
            "Vasas Gabor EGE EgrP/W1712",
            "Vass Tamas EGE EgrP/W165",
            "Vaszlik Gergely EGE EgrP/TEF3",
            "Vehoczki Annamária",
            "Veiner Zoltan EGE EgrP/W145",
            "Vereb Miklos EGE EgrP/W112",
            "Vereb Szandra EGE EgrP/PJM",
            "Verebelyi Tibor EGE EgrP/W155",
            "Veres Adam Andras EGE EgrP/W1751",
            "Veres Bela EGE AS/QMC3-Egr",
            "Veres Mate EGE EgrP/ENG2",
            "Vig Sandor EGE EgrP/LOM",
            "Vilmanyi Imre EGE EgrP/PT",
            "Vilmanyi Zsolt Janos EGE EgrP/W117",
            "Vincze Judit EGE EgrP/PC *",
            "Vincze Peter EGE EgrP/W154",
            "Vincze Zsolt EGE EgrP/TEF3 *",
            "Virag Zoltan EGE CP/PPP22-ER",
            "Voelgyi Laszlo EGE EgrP/ENG4",
            "Vojtonovszki Viktor EGE EgrP/LOM",
            "Vona Gabor EGE CP/PQA1-Egr",
            "Vrabik Gabor EGE EgrP/TEF3",
            "Zahoczki Istvan EGE EgrP/W153",
            "Zay Attila EGE EgrP/W154",
            "Zbisko Katalin EGE EgrP/HRL2 *",
            "Zelina Sandor Mate EGE EgrP/W152",
            "Zodi Zita EGE EgrP/LOI",
            "Zomborszki Gyoergy EGE EgrP/LOM",
            "Zsamboki Krisztian EGE EgrP/W135",
            "Zsiga Gabor EGE AS/QMP-Egr",
            "Zsitva Zsolt EGE EgrP/ENG4",
            "Zsoter Krisztian EGE EgrP/CTG3 *",
            "Zvara Tibor EGE EgrP/ENG1"});
            this.comboBox1.Location = new System.Drawing.Point(127, 46);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(230, 24);
            this.comboBox1.TabIndex = 6;
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(463, 255);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.statusStrip2);
            this.Controls.Add(this.textBox4);
            this.Controls.Add(this.textBox3);
            this.Controls.Add(this.textBox2);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.statusStrip1);
            this.Name = "Form1";
            this.Text = "VPRFORALL";
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.statusStrip2.ResumeLayout(false);
            this.statusStrip2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.StatusStrip statusStrip2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        private System.Windows.Forms.ComboBox comboBox1;
    }
}

